# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    jdkVersionOption: '1.8'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    
# get the standalone Nexus IQ CLI
# https://help.sonatype.com/iqserver/integrations/nexus-iq-cli#NexusIQCLI-Linux

- task: CmdLine@2
  inputs:
    script: |
          wget -qO- https://repo.sonatype.com/repository/sonatype-hosted/pki/deb-gpg/GPG-KEY-sonatype-apt-hosted.asc | \
          gpg --dearmor | \
          sudo tee /usr/share/keyrings/sonatype-apt-hosted.gpg >/dev/null
    displayName: Download the public GPG signing key and add the key to your apt sources keyring

- task: CmdLine@2
  inputs:
    script: |
         sudo wget -P /etc/apt/sources.list.d/ https://repo.sonatype.com/repository/sonatype-hosted/deb/sonatype-hosted.list
    displayName: Add the repository to your sources
    
- task: CmdLine@2
  inputs:
    script: sudo apt-get update && sudo apt-get install nexus-iq-cli
    displayName: Install the application via apt-get    

- task: CmdLine@2
  inputs:
    script: 'ls -lrt && ls -lrt target'
    displayName: List files
    
- task: CmdLine@2
  inputs:
    script: $(NEXUS_IQ_CLI) -v
    displayName: Check Nexus IQ CLI version

# nexus-iq-cli -s http://localhost:8070 -a admin:admin123 -i webgoat2 target/WebGoat-*.war
- task: CmdLine@2
  inputs:
   script: $(NEXUS_IQ_CLI) -s $(NEXUS_IQ_URL) -a $(NEXUS_IQ_USER):$(NEXUS_IQ_PWD) -i $(APPLICATION_NAME) $(SCAN_TARGET)
   displayName: Run Nexus IQ scan
    
