# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    jdkVersionOption: '1.8'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: CmdLine@2
  inputs:
    script: 'ls -l'
    
- task: CmdLine@2
  inputs:
    script: 'bash nexus-iq-cli -v'

- task: CmdLine@2
  inputs:
    script: 'bash nexus-iq-scan.sh'
	
# - task: CmdLine@2
#   inputs:
#     script: $(NEXUS_IQ_CLI) -s $(NEXUS_IQ_URL) -a $(NEXUS_IQ_USER):$(NEXUS_IQ_PWD) $(SCAN_TARGET)
    
