
name: Build webgoat app

on: push

env:
  # these would normally set in Github secrets
  IQ_SERVER_URL: https\://7a6b-2a00-23c7-6435-5a00-91de-a054-48f5-2842.ngrok-free.app
  IQ_USER: admin
  IQ_PWD: admin123
  IQ_APP: webgoat2_gha
  BUILD_ARTEFACT: target/*.war

  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn --batch-mode clean package -Dmaven.test.skip=true 

    - name: What have we got? 
      run: ls -l target/

    - name: Sonatype IQ scan 
      run: echo 'Staring Sonatype IQ scan'

    - name: Evaluate with Sonatype CLI
      id: evaluate
      uses: sonatype/actions/evaluate@v1
      with:
        iq-server-url: ${{IQ_SERVER_URL}}
        username: ${{IQ_USER}}
        password: ${{IQ_PWD}}
        application-id: ${{IQ_APP}}
        scan-targets: ${{BUILD_ARTEFACT}}
    
    # Fetch the SBOM file associated with the previous Sonatype CLI run
    - name: Fetch the SBOM
      uses: sonatype/actions/fetch-sbom@v1
      if: ( success() || failure() ) && steps.evaluate.outputs.scan-id
      with:
        iq-server-url: ${{IQ_SERVER_URL}}
        username: ${{IQ_USER}}
        password: ${{IQ_PWD}}
        application-id: ${{IQ_APP}}
        scan-id: ${{ steps.evaluate.outputs.scan-id }}
        sbom-standard: cyclonedx
        sbom-version: 1.5
        artifact-name: ${{BUILD_ARTEFACT}}-sbom

    - name: Run if no fail 
      run: echo 'This step should NOT run if the IQ scan found critical violations'
     
   
